### ISSUE TITLE
How to inform the Armor training

### ISSUE THREAD

**Issue by raulrozza** [vkdolea/age-system#23]
Is there a way to inform the character's armor training, to avoid de decrease in defense when equipping an armor with armor penalty?

I am using the sheet to setup a Dragon AGE Campaign.

## Current Behavior

Both the Defense and Speed decreases on equipping the armor

![image](https://user-images.githubusercontent.com/38353761/106013950-bd79b700-609b-11eb-8824-a5864945ba12.png) ![image](https://user-images.githubusercontent.com/38353761/106013983-c4a0c500-609b-11eb-9c24-55026eb6db12.png) ![image](https://user-images.githubusercontent.com/38353761/106014033-d2564a80-609b-11eb-9ba2-414d6169b8ad.png)

## Intended Behavior

Only the Speed decreases, if able to inform the armor training.

**Comment by vkdolea** [comment]
Currently there is no automation for this issue. In newer version of the system I added Speed in the list of Modificators. You could set Speed instead of Armor Penalty for applicable characters. Actual version is 0.3.1. If your system is not updating to it when you click the Update button on FoundryVTT, you can remove the system and install it again. This is not expected to change parameters on your World folder, but I recommend having a backup folder.

**Comment by raulrozza** [comment]
Thanks! I'm set the Speed instead of Armor Penalty in the character's sheet, if they don't have the proper training.
