### ISSUE TITLE
Actor: Organization focus error & 'invisible' description field

### ISSUE THREAD

**Issue by Alis-72** [vkdolea/age-system#82]
Organization sheet does not allow you to add Focuses, only prompts error "Character focuses cannot be..."
 ("org focus" checkbox makes no difference).
 
Also in Organization sheet the description field does not show text written in the field after saving. Clicking edit reveals text so it is there.

Tested on 
AGE System(Unofficial v1.1.7
Foundry v10 286

**Comment by vkdolea** [comment]
Description is something I have to solve. Focus issue is actually an issu to be addressed on Focus sheet, before adding it to Organization sheet.

Check the box on sidebar to indicate that the Focus is organization Focus. Otherwise the system will assume the Focus is a Character Focus. Please confirm it will address the Focus issue.

I will leave this issue opened until I release a fix for the description field.

**Comment by Alis-72** [comment]
Just tested without any modules, Org focus checkbox checked and item sheet closed before trying to add to OrgSheet. Still get error and focus not added.
![image](https://user-images.githubusercontent.com/75221971/194290073-5ee9abee-4f09-4a8c-b17d-79685cc339f0.png)

**Comment by vkdolea** [comment]
New version released fixing both issues.
